{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": 1,
   "id": "1465c947",
   "metadata": {
    "_cell_guid": "4096ea21-ffcc-4f3b-af4d-482409fb5a94",
    "_uuid": "77c5b1b9-5d80-4df2-94ca-691d2e0c8b7a",
    "collapsed": false,
    "execution": {
     "iopub.execute_input": "2022-08-09T18:09:43.128284Z",
     "iopub.status.busy": "2022-08-09T18:09:43.127574Z",
     "iopub.status.idle": "2022-08-09T18:09:55.731127Z",
     "shell.execute_reply": "2022-08-09T18:09:55.730392Z",
     "shell.execute_reply.started": "2022-08-09T17:59:56.055198Z"
    },
    "id": "9x9015p-H-XI",
    "jupyter": {
     "outputs_hidden": false
    },
    "papermill": {
     "duration": 12.620687,
     "end_time": "2022-08-09T18:09:55.731301",
     "exception": false,
     "start_time": "2022-08-09T18:09:43.110614",
     "status": "completed"
    },
    "tags": []
   },
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "\u001b[31mERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.\r\n",
      "tensorflow-cloud 0.1.13 requires tensorflow-datasets<3.1.0, but you have tensorflow-datasets 4.4.0 which is incompatible.\u001b[0m\r\n",
      "\u001b[33mWARNING: Running pip as the 'root' user can result in broken permissions and conflicting behaviour with the system package manager. It is recommended to use a virtual environment instead: https://pip.pypa.io/warnings/venv\u001b[0m\r\n"
     ]
    }
   ],
   "source": [
    "!pip install -q tensorflow_datasets==4.4.0"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 2,
   "id": "488339a7",
   "metadata": {
    "execution": {
     "iopub.execute_input": "2022-08-09T18:09:55.754499Z",
     "iopub.status.busy": "2022-08-09T18:09:55.753184Z",
     "iopub.status.idle": "2022-08-09T18:09:57.605559Z",
     "shell.execute_reply": "2022-08-09T18:09:57.604982Z",
     "shell.execute_reply.started": "2022-08-09T18:00:08.984353Z"
    },
    "papermill": {
     "duration": 1.868127,
     "end_time": "2022-08-09T18:09:57.605720",
     "exception": false,
     "start_time": "2022-08-09T18:09:55.737593",
     "status": "completed"
    },
    "tags": []
   },
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Cloning into '/kaggle/working/repo'...\r\n",
      "remote: Enumerating objects: 69, done.\u001b[K\r\n",
      "remote: Counting objects: 100% (69/69), done.\u001b[K\r\n",
      "remote: Compressing objects: 100% (67/67), done.\u001b[K\r\n",
      "remote: Total 69 (delta 21), reused 0 (delta 0), pack-reused 0\u001b[K\r\n",
      "Unpacking objects: 100% (69/69), done.\r\n"
     ]
    }
   ],
   "source": [
    "!git clone https://github.com/dleqhuy/cbis_ddsm_train.git /kaggle/working/repo"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 3,
   "id": "bc218c91",
   "metadata": {
    "execution": {
     "iopub.execute_input": "2022-08-09T18:09:57.623931Z",
     "iopub.status.busy": "2022-08-09T18:09:57.622942Z",
     "iopub.status.idle": "2022-08-09T18:09:57.625270Z",
     "shell.execute_reply": "2022-08-09T18:09:57.625960Z",
     "shell.execute_reply.started": "2022-08-09T18:00:10.741683Z"
    },
    "papermill": {
     "duration": 0.014054,
     "end_time": "2022-08-09T18:09:57.626142",
     "exception": false,
     "start_time": "2022-08-09T18:09:57.612088",
     "status": "completed"
    },
    "tags": []
   },
   "outputs": [],
   "source": [
    "import os\n",
    "os.chdir('/kaggle/working/repo/')"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 4,
   "id": "bcb6fc5d",
   "metadata": {
    "execution": {
     "iopub.execute_input": "2022-08-09T18:09:57.642630Z",
     "iopub.status.busy": "2022-08-09T18:09:57.641638Z",
     "iopub.status.idle": "2022-08-09T18:17:32.361833Z",
     "shell.execute_reply": "2022-08-09T18:17:32.362926Z",
     "shell.execute_reply.started": "2022-08-09T18:00:10.749409Z"
    },
    "papermill": {
     "duration": 454.730634,
     "end_time": "2022-08-09T18:17:32.363295",
     "exception": false,
     "start_time": "2022-08-09T18:09:57.632661",
     "status": "completed"
    },
    "tags": []
   },
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "2022-08-09 18:10:01.647685: W tensorflow/stream_executor/platform/default/dso_loader.cc:60] Could not load dynamic library 'libcudart.so.11.0'; dlerror: libcudart.so.11.0: cannot open shared object file: No such file or directory; LD_LIBRARY_PATH: /opt/conda/lib\r\n",
      "2022-08-09 18:10:01.647779: I tensorflow/stream_executor/cuda/cudart_stub.cc:29] Ignore above cudart dlerror if you do not have a GPU set up on your machine.\r\n",
      "2022-08-09 18:10:07.828114: I tensorflow/compiler/jit/xla_cpu_device.cc:41] Not creating XLA devices, tf_xla_enable_xla_devices not set\r\n",
      "2022-08-09 18:10:07.830991: W tensorflow/stream_executor/platform/default/dso_loader.cc:60] Could not load dynamic library 'libcuda.so.1'; dlerror: libcuda.so.1: cannot open shared object file: No such file or directory; LD_LIBRARY_PATH: /opt/conda/lib\r\n",
      "2022-08-09 18:10:07.831045: W tensorflow/stream_executor/cuda/cuda_driver.cc:326] failed call to cuInit: UNKNOWN ERROR (303)\r\n",
      "2022-08-09 18:10:07.831086: I tensorflow/stream_executor/cuda/cuda_diagnostics.cc:156] kernel driver does not appear to be running on this host (0548f67eda3f): /proc/driver/nvidia/version does not exist\r\n",
      "2022-08-09 18:10:07.833799: I tensorflow/core/platform/cpu_feature_guard.cc:142] This TensorFlow binary is optimized with oneAPI Deep Neural Network Library (oneDNN) to use the following CPU instructions in performance-critical operations:  AVX2 FMA\r\n",
      "To enable them in other operations, rebuild TensorFlow with the appropriate compiler flags.\r\n",
      "2022-08-09 18:10:07.835454: I tensorflow/compiler/jit/xla_gpu_device.cc:99] Not creating XLA devices, tf_xla_enable_xla_devices not set\r\n",
      "2022-08-09 18:10:07.840925: I tensorflow/compiler/jit/xla_gpu_device.cc:99] Not creating XLA devices, tf_xla_enable_xla_devices not set\r\n",
      "2022-08-09 18:10:07.867996: I tensorflow/core/distributed_runtime/rpc/grpc_channel.cc:301] Initialize GrpcChannelCache for job worker -> {0 -> 10.0.0.2:8470}\r\n",
      "2022-08-09 18:10:07.868155: I tensorflow/core/distributed_runtime/rpc/grpc_channel.cc:301] Initialize GrpcChannelCache for job localhost -> {0 -> localhost:30061}\r\n",
      "2022-08-09 18:10:07.885989: I tensorflow/core/distributed_runtime/rpc/grpc_channel.cc:301] Initialize GrpcChannelCache for job worker -> {0 -> 10.0.0.2:8470}\r\n",
      "2022-08-09 18:10:07.886166: I tensorflow/core/distributed_runtime/rpc/grpc_channel.cc:301] Initialize GrpcChannelCache for job localhost -> {0 -> localhost:30061}\r\n",
      "2022-08-09 18:10:07.887895: I tensorflow/core/distributed_runtime/rpc/grpc_server_lib.cc:411] Started server with target: grpc://localhost:30061\r\n",
      "I0809 18:10:07.888599 139958598170432 remote.py:218] Entering into master device scope: /job:worker/replica:0/task:0/device:CPU:0\r\n",
      "I0809 18:10:07.889455 139958598170432 tpu_strategy_util.py:74] Initializing the TPU system: grpc://10.0.0.2:8470\r\n",
      "I0809 18:10:13.592530 139958598170432 tpu_strategy_util.py:109] Clearing out eager caches\r\n",
      "I0809 18:10:13.601402 139958598170432 tpu_strategy_util.py:133] Finished initializing TPU system.\r\n",
      "W0809 18:10:13.605055 139958598170432 tpu_strategy.py:514] `tf.distribute.experimental.TPUStrategy` is deprecated, please use  the non experimental symbol `tf.distribute.TPUStrategy` instead.\r\n",
      "I0809 18:10:13.606276 139958598170432 tpu_system_metadata.py:159] Found TPU system:\r\n",
      "I0809 18:10:13.606472 139958598170432 tpu_system_metadata.py:160] *** Num TPU Cores: 8\r\n",
      "I0809 18:10:13.606795 139958598170432 tpu_system_metadata.py:161] *** Num TPU Workers: 1\r\n",
      "I0809 18:10:13.606873 139958598170432 tpu_system_metadata.py:163] *** Num TPU Cores Per Worker: 8\r\n",
      "I0809 18:10:13.606946 139958598170432 tpu_system_metadata.py:165] *** Available Device: _DeviceAttributes(/job:localhost/replica:0/task:0/device:CPU:0, CPU, 0, 0)\r\n",
      "I0809 18:10:13.607126 139958598170432 tpu_system_metadata.py:165] *** Available Device: _DeviceAttributes(/job:worker/replica:0/task:0/device:CPU:0, CPU, 0, 0)\r\n",
      "I0809 18:10:13.607201 139958598170432 tpu_system_metadata.py:165] *** Available Device: _DeviceAttributes(/job:worker/replica:0/task:0/device:TPU:0, TPU, 0, 0)\r\n",
      "I0809 18:10:13.607265 139958598170432 tpu_system_metadata.py:165] *** Available Device: _DeviceAttributes(/job:worker/replica:0/task:0/device:TPU:1, TPU, 0, 0)\r\n",
      "I0809 18:10:13.607336 139958598170432 tpu_system_metadata.py:165] *** Available Device: _DeviceAttributes(/job:worker/replica:0/task:0/device:TPU:2, TPU, 0, 0)\r\n",
      "I0809 18:10:13.607403 139958598170432 tpu_system_metadata.py:165] *** Available Device: _DeviceAttributes(/job:worker/replica:0/task:0/device:TPU:3, TPU, 0, 0)\r\n",
      "I0809 18:10:13.607470 139958598170432 tpu_system_metadata.py:165] *** Available Device: _DeviceAttributes(/job:worker/replica:0/task:0/device:TPU:4, TPU, 0, 0)\r\n",
      "I0809 18:10:13.607560 139958598170432 tpu_system_metadata.py:165] *** Available Device: _DeviceAttributes(/job:worker/replica:0/task:0/device:TPU:5, TPU, 0, 0)\r\n",
      "I0809 18:10:13.607642 139958598170432 tpu_system_metadata.py:165] *** Available Device: _DeviceAttributes(/job:worker/replica:0/task:0/device:TPU:6, TPU, 0, 0)\r\n",
      "I0809 18:10:13.607714 139958598170432 tpu_system_metadata.py:165] *** Available Device: _DeviceAttributes(/job:worker/replica:0/task:0/device:TPU:7, TPU, 0, 0)\r\n",
      "I0809 18:10:13.607780 139958598170432 tpu_system_metadata.py:165] *** Available Device: _DeviceAttributes(/job:worker/replica:0/task:0/device:TPU_SYSTEM:0, TPU_SYSTEM, 0, 0)\r\n",
      "I0809 18:10:13.607844 139958598170432 tpu_system_metadata.py:165] *** Available Device: _DeviceAttributes(/job:worker/replica:0/task:0/device:XLA_CPU:0, XLA_CPU, 0, 0)\r\n",
      "2022-08-09 18:10:13.967748: I tensorflow/core/platform/cloud/google_auth_provider.cc:180] Attempting an empty bearer token since no token was retrieved from files, and GCE metadata check was skipped.\r\n",
      "2022-08-09 18:10:14.045317: I tensorflow/core/platform/cloud/google_auth_provider.cc:180] Attempting an empty bearer token since no token was retrieved from files, and GCE metadata check was skipped.\r\n",
      "2022-08-09 18:10:14.119325: I tensorflow/core/platform/cloud/google_auth_provider.cc:180] Attempting an empty bearer token since no token was retrieved from files, and GCE metadata check was skipped.\r\n",
      "2022-08-09 18:10:14.187730: I tensorflow/core/platform/cloud/google_auth_provider.cc:180] Attempting an empty bearer token since no token was retrieved from files, and GCE metadata check was skipped.\r\n",
      "2022-08-09 18:10:14.267433: I tensorflow/core/platform/cloud/google_auth_provider.cc:180] Attempting an empty bearer token since no token was retrieved from files, and GCE metadata check was skipped.\r\n",
      "2022-08-09 18:10:14.341254: I tensorflow/core/platform/cloud/google_auth_provider.cc:180] Attempting an empty bearer token since no token was retrieved from files, and GCE metadata check was skipped.\r\n",
      "2022-08-09 18:10:14.407959: I tensorflow/core/platform/cloud/google_auth_provider.cc:180] Attempting an empty bearer token since no token was retrieved from files, and GCE metadata check was skipped.\r\n",
      "2022-08-09 18:10:14.482694: I tensorflow/core/platform/cloud/google_auth_provider.cc:180] Attempting an empty bearer token since no token was retrieved from files, and GCE metadata check was skipped.\r\n",
      "2022-08-09 18:10:14.551584: I tensorflow/core/platform/cloud/google_auth_provider.cc:180] Attempting an empty bearer token since no token was retrieved from files, and GCE metadata check was skipped.\r\n",
      "2022-08-09 18:10:14.715349: I tensorflow/core/platform/cloud/google_auth_provider.cc:180] Attempting an empty bearer token since no token was retrieved from files, and GCE metadata check was skipped.\r\n",
      "2022-08-09 18:10:14.794863: I tensorflow/core/platform/cloud/google_auth_provider.cc:180] Attempting an empty bearer token since no token was retrieved from files, and GCE metadata check was skipped.\r\n",
      "I0809 18:10:14.875739 139958598170432 dataset_info.py:358] Load dataset info from gs://kds-f2001cb46986c692a950ae60446dc32313db0b3086467d220d725445/patch/1.0.0\r\n",
      "2022-08-09 18:10:14.925412: I tensorflow/core/platform/cloud/google_auth_provider.cc:180] Attempting an empty bearer token since no token was retrieved from files, and GCE metadata check was skipped.\r\n",
      "2022-08-09 18:10:15.050519: I tensorflow/core/platform/cloud/google_auth_provider.cc:180] Attempting an empty bearer token since no token was retrieved from files, and GCE metadata check was skipped.\r\n",
      "2022-08-09 18:10:15.122686: I tensorflow/core/platform/cloud/google_auth_provider.cc:180] Attempting an empty bearer token since no token was retrieved from files, and GCE metadata check was skipped.\r\n",
      "2022-08-09 18:10:15.237737: I tensorflow/core/platform/cloud/google_auth_provider.cc:180] Attempting an empty bearer token since no token was retrieved from files, and GCE metadata check was skipped.\r\n",
      "2022-08-09 18:10:15.316990: I tensorflow/core/platform/cloud/google_auth_provider.cc:180] Attempting an empty bearer token since no token was retrieved from files, and GCE metadata check was skipped.\r\n",
      "2022-08-09 18:10:15.381186: I tensorflow/core/platform/cloud/google_auth_provider.cc:180] Attempting an empty bearer token since no token was retrieved from files, and GCE metadata check was skipped.\r\n",
      "2022-08-09 18:10:15.452550: I tensorflow/core/platform/cloud/google_auth_provider.cc:180] Attempting an empty bearer token since no token was retrieved from files, and GCE metadata check was skipped.\r\n",
      "I0809 18:10:15.518834 139958598170432 dataset_builder.py:351] Reusing dataset patch (gs://kds-f2001cb46986c692a950ae60446dc32313db0b3086467d220d725445/patch/1.0.0)\r\n",
      "I0809 18:10:15.519217 139958598170432 logging_logger.py:36] Constructing tf.data.Dataset patch for split ['train', 'test', 'val'], from gs://kds-f2001cb46986c692a950ae60446dc32313db0b3086467d220d725445/patch/1.0.0\r\n",
      "2022-08-09 18:10:15.519469: I tensorflow/core/platform/cloud/google_auth_provider.cc:180] Attempting an empty bearer token since no token was retrieved from files, and GCE metadata check was skipped.\r\n",
      "Downloading data from https://storage.googleapis.com/tensorflow/keras-applications/vgg16/vgg16_weights_tf_dim_ordering_tf_kernels_notop.h5\r\n",
      "58892288/58889256 [==============================] - 0s 0us/step\r\n",
      "I0809 18:10:18.825531 139958598170432 train_patch.py:145] Huấn luyện giai đoạn 1 với lớp cuối cùng\r\n",
      "Epoch 1/3\r\n",
      "445/445 [==============================] - 21s 47ms/step - loss: 1.1685 - accuracy: 0.4881 - val_loss: 0.9635 - val_accuracy: 0.5305\r\n",
      "\r\n",
      "Epoch 00001: val_accuracy improved from -inf to 0.53047, saving model to ./vgg16.h5\r\n",
      "Epoch 2/3\r\n",
      "445/445 [==============================] - 12s 26ms/step - loss: 0.9664 - accuracy: 0.5417 - val_loss: 0.9558 - val_accuracy: 0.5420\r\n",
      "\r\n",
      "Epoch 00002: val_accuracy improved from 0.53047 to 0.54199, saving model to ./vgg16.h5\r\n",
      "Epoch 3/3\r\n",
      "445/445 [==============================] - 11s 26ms/step - loss: 0.9605 - accuracy: 0.5426 - val_loss: 0.9523 - val_accuracy: 0.5340\r\n",
      "\r\n",
      "Epoch 00003: val_accuracy did not improve from 0.54199\r\n",
      "I0809 18:11:05.378719 139958598170432 train_patch.py:157] Huấn luyện giai đoạn 2 mở đóng băng từ layer 0 đến top layer nb: 10\r\n",
      "Epoch 3/13\r\n",
      "445/445 [==============================] - 25s 57ms/step - loss: 0.9875 - accuracy: 0.5086 - val_loss: 0.8835 - val_accuracy: 0.6010\r\n",
      "\r\n",
      "Epoch 00003: val_accuracy improved from 0.54199 to 0.60098, saving model to ./vgg16.h5\r\n",
      "Epoch 4/13\r\n",
      "445/445 [==============================] - 11s 26ms/step - loss: 0.8228 - accuracy: 0.6177 - val_loss: 0.7453 - val_accuracy: 0.6670\r\n",
      "\r\n",
      "Epoch 00004: val_accuracy improved from 0.60098 to 0.66699, saving model to ./vgg16.h5\r\n",
      "Epoch 5/13\r\n",
      "445/445 [==============================] - 12s 26ms/step - loss: 0.7288 - accuracy: 0.6771 - val_loss: 0.6958 - val_accuracy: 0.7125\r\n",
      "\r\n",
      "Epoch 00005: val_accuracy improved from 0.66699 to 0.71250, saving model to ./vgg16.h5\r\n",
      "Epoch 6/13\r\n",
      "445/445 [==============================] - 11s 26ms/step - loss: 0.6691 - accuracy: 0.7184 - val_loss: 0.6860 - val_accuracy: 0.7133\r\n",
      "\r\n",
      "Epoch 00006: val_accuracy improved from 0.71250 to 0.71328, saving model to ./vgg16.h5\r\n",
      "Epoch 7/13\r\n",
      "445/445 [==============================] - 11s 26ms/step - loss: 0.6322 - accuracy: 0.7340 - val_loss: 0.6360 - val_accuracy: 0.7461\r\n",
      "\r\n",
      "Epoch 00007: val_accuracy improved from 0.71328 to 0.74609, saving model to ./vgg16.h5\r\n",
      "Epoch 8/13\r\n",
      "445/445 [==============================] - 12s 26ms/step - loss: 0.6017 - accuracy: 0.7515 - val_loss: 0.6190 - val_accuracy: 0.7607\r\n",
      "\r\n",
      "Epoch 00008: val_accuracy improved from 0.74609 to 0.76074, saving model to ./vgg16.h5\r\n",
      "Epoch 9/13\r\n",
      "445/445 [==============================] - 11s 26ms/step - loss: 0.5831 - accuracy: 0.7624 - val_loss: 0.7222 - val_accuracy: 0.7184\r\n",
      "\r\n",
      "Epoch 00009: val_accuracy did not improve from 0.76074\r\n",
      "Epoch 10/13\r\n",
      "445/445 [==============================] - 12s 26ms/step - loss: 0.5664 - accuracy: 0.7701 - val_loss: 0.6285 - val_accuracy: 0.7605\r\n",
      "\r\n",
      "Epoch 00010: val_accuracy did not improve from 0.76074\r\n",
      "Epoch 11/13\r\n",
      "445/445 [==============================] - 11s 26ms/step - loss: 0.5502 - accuracy: 0.7783 - val_loss: 0.6352 - val_accuracy: 0.7523\r\n",
      "\r\n",
      "Epoch 00011: val_accuracy did not improve from 0.76074\r\n",
      "Epoch 12/13\r\n",
      "445/445 [==============================] - 11s 26ms/step - loss: 0.5426 - accuracy: 0.7824 - val_loss: 0.6462 - val_accuracy: 0.7508\r\n",
      "\r\n",
      "Epoch 00012: val_accuracy did not improve from 0.76074\r\n",
      "Epoch 13/13\r\n",
      "445/445 [==============================] - 12s 27ms/step - loss: 0.5254 - accuracy: 0.7906 - val_loss: 0.7200 - val_accuracy: 0.7441\r\n",
      "\r\n",
      "Epoch 00013: val_accuracy did not improve from 0.76074\r\n",
      "I0809 18:13:36.163584 139958598170432 train_patch.py:169] Mở đóng băng mô hình, huấn luyện giai đoạn 3\r\n",
      "Epoch 13/50\r\n",
      "445/445 [==============================] - 32s 72ms/step - loss: 0.4852 - accuracy: 0.8065 - val_loss: 0.6075 - val_accuracy: 0.7746\r\n",
      "\r\n",
      "Epoch 00013: val_accuracy improved from 0.76074 to 0.77461, saving model to ./vgg16.h5\r\n",
      "Epoch 14/50\r\n",
      "445/445 [==============================] - 15s 33ms/step - loss: 0.4680 - accuracy: 0.8151 - val_loss: 0.5968 - val_accuracy: 0.7791\r\n",
      "\r\n",
      "Epoch 00014: val_accuracy improved from 0.77461 to 0.77910, saving model to ./vgg16.h5\r\n",
      "Epoch 15/50\r\n",
      "445/445 [==============================] - 15s 34ms/step - loss: 0.4617 - accuracy: 0.8169 - val_loss: 0.5594 - val_accuracy: 0.7936\r\n",
      "\r\n",
      "Epoch 00015: val_accuracy improved from 0.77910 to 0.79355, saving model to ./vgg16.h5\r\n",
      "Epoch 16/50\r\n",
      "445/445 [==============================] - 15s 34ms/step - loss: 0.4534 - accuracy: 0.8211 - val_loss: 0.5804 - val_accuracy: 0.7918\r\n",
      "\r\n",
      "Epoch 00016: val_accuracy did not improve from 0.79355\r\n",
      "Epoch 17/50\r\n",
      "445/445 [==============================] - 15s 34ms/step - loss: 0.4461 - accuracy: 0.8223 - val_loss: 0.5663 - val_accuracy: 0.7910\r\n",
      "\r\n",
      "Epoch 00017: val_accuracy did not improve from 0.79355\r\n",
      "Epoch 18/50\r\n",
      "445/445 [==============================] - 15s 34ms/step - loss: 0.4396 - accuracy: 0.8249 - val_loss: 0.6334 - val_accuracy: 0.7750\r\n",
      "\r\n",
      "Epoch 00018: val_accuracy did not improve from 0.79355\r\n",
      "Epoch 19/50\r\n",
      "445/445 [==============================] - 15s 34ms/step - loss: 0.4368 - accuracy: 0.8269 - val_loss: 0.5758 - val_accuracy: 0.7951\r\n",
      "\r\n",
      "Epoch 00019: val_accuracy improved from 0.79355 to 0.79512, saving model to ./vgg16.h5\r\n",
      "Epoch 20/50\r\n",
      "445/445 [==============================] - 15s 33ms/step - loss: 0.4286 - accuracy: 0.8307 - val_loss: 0.5601 - val_accuracy: 0.8055\r\n",
      "\r\n",
      "Epoch 00020: val_accuracy improved from 0.79512 to 0.80547, saving model to ./vgg16.h5\r\n",
      "Epoch 21/50\r\n",
      "445/445 [==============================] - 15s 35ms/step - loss: 0.4220 - accuracy: 0.8310 - val_loss: 0.5626 - val_accuracy: 0.8045\r\n",
      "\r\n",
      "Epoch 00021: val_accuracy did not improve from 0.80547\r\n",
      "Epoch 22/50\r\n",
      "445/445 [==============================] - 15s 33ms/step - loss: 0.4188 - accuracy: 0.8356 - val_loss: 0.6219 - val_accuracy: 0.7818\r\n",
      "\r\n",
      "Epoch 00022: val_accuracy did not improve from 0.80547\r\n",
      "Epoch 23/50\r\n",
      "445/445 [==============================] - 15s 34ms/step - loss: 0.4088 - accuracy: 0.8399 - val_loss: 0.6023 - val_accuracy: 0.7873\r\n",
      "\r\n",
      "Epoch 00023: val_accuracy did not improve from 0.80547\r\n",
      "Epoch 24/50\r\n",
      "445/445 [==============================] - 15s 34ms/step - loss: 0.4048 - accuracy: 0.8391 - val_loss: 0.5742 - val_accuracy: 0.7982\r\n",
      "\r\n",
      "Epoch 00024: val_accuracy did not improve from 0.80547\r\n",
      "Epoch 25/50\r\n",
      "445/445 [==============================] - 15s 34ms/step - loss: 0.3975 - accuracy: 0.8424 - val_loss: 0.6159 - val_accuracy: 0.7912\r\n",
      "\r\n",
      "Epoch 00025: val_accuracy did not improve from 0.80547\r\n",
      "I0809 18:17:22.850811 139958598170432 train_patch.py:185] Kiểm tra trên tập test\r\n",
      "148/148 [==============================] - 7s 21ms/step - loss: 0.4664 - accuracy: 0.8291\r\n"
     ]
    }
   ],
   "source": [
    "!python train_patch.py  --batch_size=64\\\n",
    "                        --model_name='vgg16'\\\n",
    "                        --drop_out=0.5\\\n",
    "                        --save_dir='./vgg16.h5'\\\n",
    "                        --num_class=3\\\n",
    "                        --lr_step1=0.001\\\n",
    "                        --lr_step2=0.0001\\\n",
    "                        --lr_step3=0.00001\\\n",
    "                        --epochs_step1=3\\\n",
    "                        --epochs_step2=10\\\n",
    "                        --epochs_step3=37"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 5,
   "id": "742f0c40",
   "metadata": {
    "execution": {
     "iopub.execute_input": "2022-08-09T18:17:32.479645Z",
     "iopub.status.busy": "2022-08-09T18:17:32.478588Z",
     "iopub.status.idle": "2022-08-09T18:28:53.560934Z",
     "shell.execute_reply": "2022-08-09T18:28:53.560279Z"
    },
    "papermill": {
     "duration": 681.142624,
     "end_time": "2022-08-09T18:28:53.561167",
     "exception": false,
     "start_time": "2022-08-09T18:17:32.418543",
     "status": "completed"
    },
    "tags": []
   },
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "2022-08-09 18:17:35.665384: W tensorflow/stream_executor/platform/default/dso_loader.cc:60] Could not load dynamic library 'libcudart.so.11.0'; dlerror: libcudart.so.11.0: cannot open shared object file: No such file or directory; LD_LIBRARY_PATH: /opt/conda/lib\r\n",
      "2022-08-09 18:17:35.665446: I tensorflow/stream_executor/cuda/cudart_stub.cc:29] Ignore above cudart dlerror if you do not have a GPU set up on your machine.\r\n",
      "2022-08-09 18:17:38.622195: I tensorflow/compiler/jit/xla_cpu_device.cc:41] Not creating XLA devices, tf_xla_enable_xla_devices not set\r\n",
      "2022-08-09 18:17:38.622466: W tensorflow/stream_executor/platform/default/dso_loader.cc:60] Could not load dynamic library 'libcuda.so.1'; dlerror: libcuda.so.1: cannot open shared object file: No such file or directory; LD_LIBRARY_PATH: /opt/conda/lib\r\n",
      "2022-08-09 18:17:38.622501: W tensorflow/stream_executor/cuda/cuda_driver.cc:326] failed call to cuInit: UNKNOWN ERROR (303)\r\n",
      "2022-08-09 18:17:38.622542: I tensorflow/stream_executor/cuda/cuda_diagnostics.cc:156] kernel driver does not appear to be running on this host (0548f67eda3f): /proc/driver/nvidia/version does not exist\r\n",
      "2022-08-09 18:17:38.623162: I tensorflow/core/platform/cpu_feature_guard.cc:142] This TensorFlow binary is optimized with oneAPI Deep Neural Network Library (oneDNN) to use the following CPU instructions in performance-critical operations:  AVX2 FMA\r\n",
      "To enable them in other operations, rebuild TensorFlow with the appropriate compiler flags.\r\n",
      "2022-08-09 18:17:38.623499: I tensorflow/compiler/jit/xla_gpu_device.cc:99] Not creating XLA devices, tf_xla_enable_xla_devices not set\r\n",
      "2022-08-09 18:17:38.624127: I tensorflow/compiler/jit/xla_gpu_device.cc:99] Not creating XLA devices, tf_xla_enable_xla_devices not set\r\n",
      "2022-08-09 18:17:38.629571: I tensorflow/core/distributed_runtime/rpc/grpc_channel.cc:301] Initialize GrpcChannelCache for job worker -> {0 -> 10.0.0.2:8470}\r\n",
      "2022-08-09 18:17:38.629628: I tensorflow/core/distributed_runtime/rpc/grpc_channel.cc:301] Initialize GrpcChannelCache for job localhost -> {0 -> localhost:30178}\r\n",
      "2022-08-09 18:17:38.644367: I tensorflow/core/distributed_runtime/rpc/grpc_channel.cc:301] Initialize GrpcChannelCache for job worker -> {0 -> 10.0.0.2:8470}\r\n",
      "2022-08-09 18:17:38.644439: I tensorflow/core/distributed_runtime/rpc/grpc_channel.cc:301] Initialize GrpcChannelCache for job localhost -> {0 -> localhost:30178}\r\n",
      "2022-08-09 18:17:38.644949: I tensorflow/core/distributed_runtime/rpc/grpc_server_lib.cc:411] Started server with target: grpc://localhost:30178\r\n",
      "I0809 18:17:38.646549 139830674605888 remote.py:218] Entering into master device scope: /job:worker/replica:0/task:0/device:CPU:0\r\n",
      "I0809 18:17:38.647598 139830674605888 tpu_strategy_util.py:74] Initializing the TPU system: grpc://10.0.0.2:8470\r\n",
      "I0809 18:17:43.590527 139830674605888 tpu_strategy_util.py:109] Clearing out eager caches\r\n",
      "I0809 18:17:43.592472 139830674605888 tpu_strategy_util.py:133] Finished initializing TPU system.\r\n",
      "W0809 18:17:43.593498 139830674605888 tpu_strategy.py:514] `tf.distribute.experimental.TPUStrategy` is deprecated, please use  the non experimental symbol `tf.distribute.TPUStrategy` instead.\r\n",
      "I0809 18:17:43.594623 139830674605888 tpu_system_metadata.py:159] Found TPU system:\r\n",
      "I0809 18:17:43.594787 139830674605888 tpu_system_metadata.py:160] *** Num TPU Cores: 8\r\n",
      "I0809 18:17:43.595201 139830674605888 tpu_system_metadata.py:161] *** Num TPU Workers: 1\r\n",
      "I0809 18:17:43.595337 139830674605888 tpu_system_metadata.py:163] *** Num TPU Cores Per Worker: 8\r\n",
      "I0809 18:17:43.595461 139830674605888 tpu_system_metadata.py:165] *** Available Device: _DeviceAttributes(/job:localhost/replica:0/task:0/device:CPU:0, CPU, 0, 0)\r\n",
      "I0809 18:17:43.595856 139830674605888 tpu_system_metadata.py:165] *** Available Device: _DeviceAttributes(/job:worker/replica:0/task:0/device:CPU:0, CPU, 0, 0)\r\n",
      "I0809 18:17:43.596153 139830674605888 tpu_system_metadata.py:165] *** Available Device: _DeviceAttributes(/job:worker/replica:0/task:0/device:TPU:0, TPU, 0, 0)\r\n",
      "I0809 18:17:43.596298 139830674605888 tpu_system_metadata.py:165] *** Available Device: _DeviceAttributes(/job:worker/replica:0/task:0/device:TPU:1, TPU, 0, 0)\r\n",
      "I0809 18:17:43.596433 139830674605888 tpu_system_metadata.py:165] *** Available Device: _DeviceAttributes(/job:worker/replica:0/task:0/device:TPU:2, TPU, 0, 0)\r\n",
      "I0809 18:17:43.596539 139830674605888 tpu_system_metadata.py:165] *** Available Device: _DeviceAttributes(/job:worker/replica:0/task:0/device:TPU:3, TPU, 0, 0)\r\n",
      "I0809 18:17:43.596692 139830674605888 tpu_system_metadata.py:165] *** Available Device: _DeviceAttributes(/job:worker/replica:0/task:0/device:TPU:4, TPU, 0, 0)\r\n",
      "I0809 18:17:43.596801 139830674605888 tpu_system_metadata.py:165] *** Available Device: _DeviceAttributes(/job:worker/replica:0/task:0/device:TPU:5, TPU, 0, 0)\r\n",
      "I0809 18:17:43.596970 139830674605888 tpu_system_metadata.py:165] *** Available Device: _DeviceAttributes(/job:worker/replica:0/task:0/device:TPU:6, TPU, 0, 0)\r\n",
      "I0809 18:17:43.597086 139830674605888 tpu_system_metadata.py:165] *** Available Device: _DeviceAttributes(/job:worker/replica:0/task:0/device:TPU:7, TPU, 0, 0)\r\n",
      "I0809 18:17:43.597206 139830674605888 tpu_system_metadata.py:165] *** Available Device: _DeviceAttributes(/job:worker/replica:0/task:0/device:TPU_SYSTEM:0, TPU_SYSTEM, 0, 0)\r\n",
      "I0809 18:17:43.597301 139830674605888 tpu_system_metadata.py:165] *** Available Device: _DeviceAttributes(/job:worker/replica:0/task:0/device:XLA_CPU:0, XLA_CPU, 0, 0)\r\n",
      "2022-08-09 18:17:43.985181: I tensorflow/core/platform/cloud/google_auth_provider.cc:180] Attempting an empty bearer token since no token was retrieved from files, and GCE metadata check was skipped.\r\n",
      "2022-08-09 18:17:44.052494: I tensorflow/core/platform/cloud/google_auth_provider.cc:180] Attempting an empty bearer token since no token was retrieved from files, and GCE metadata check was skipped.\r\n",
      "2022-08-09 18:17:44.118942: I tensorflow/core/platform/cloud/google_auth_provider.cc:180] Attempting an empty bearer token since no token was retrieved from files, and GCE metadata check was skipped.\r\n",
      "2022-08-09 18:17:44.190007: I tensorflow/core/platform/cloud/google_auth_provider.cc:180] Attempting an empty bearer token since no token was retrieved from files, and GCE metadata check was skipped.\r\n",
      "2022-08-09 18:17:44.267961: I tensorflow/core/platform/cloud/google_auth_provider.cc:180] Attempting an empty bearer token since no token was retrieved from files, and GCE metadata check was skipped.\r\n",
      "2022-08-09 18:17:44.336654: I tensorflow/core/platform/cloud/google_auth_provider.cc:180] Attempting an empty bearer token since no token was retrieved from files, and GCE metadata check was skipped.\r\n",
      "2022-08-09 18:17:44.405737: I tensorflow/core/platform/cloud/google_auth_provider.cc:180] Attempting an empty bearer token since no token was retrieved from files, and GCE metadata check was skipped.\r\n",
      "2022-08-09 18:17:44.480664: I tensorflow/core/platform/cloud/google_auth_provider.cc:180] Attempting an empty bearer token since no token was retrieved from files, and GCE metadata check was skipped.\r\n",
      "2022-08-09 18:17:44.562445: I tensorflow/core/platform/cloud/google_auth_provider.cc:180] Attempting an empty bearer token since no token was retrieved from files, and GCE metadata check was skipped.\r\n",
      "2022-08-09 18:17:44.691162: I tensorflow/core/platform/cloud/google_auth_provider.cc:180] Attempting an empty bearer token since no token was retrieved from files, and GCE metadata check was skipped.\r\n",
      "2022-08-09 18:17:44.766479: I tensorflow/core/platform/cloud/google_auth_provider.cc:180] Attempting an empty bearer token since no token was retrieved from files, and GCE metadata check was skipped.\r\n",
      "I0809 18:17:44.844424 139830674605888 dataset_info.py:358] Load dataset info from gs://kds-f2001cb46986c692a950ae60446dc32313db0b3086467d220d725445/patch/1.0.0\r\n",
      "2022-08-09 18:17:44.894343: I tensorflow/core/platform/cloud/google_auth_provider.cc:180] Attempting an empty bearer token since no token was retrieved from files, and GCE metadata check was skipped.\r\n",
      "2022-08-09 18:17:45.019663: I tensorflow/core/platform/cloud/google_auth_provider.cc:180] Attempting an empty bearer token since no token was retrieved from files, and GCE metadata check was skipped.\r\n",
      "2022-08-09 18:17:45.092572: I tensorflow/core/platform/cloud/google_auth_provider.cc:180] Attempting an empty bearer token since no token was retrieved from files, and GCE metadata check was skipped.\r\n",
      "2022-08-09 18:17:45.203113: I tensorflow/core/platform/cloud/google_auth_provider.cc:180] Attempting an empty bearer token since no token was retrieved from files, and GCE metadata check was skipped.\r\n",
      "2022-08-09 18:17:45.331475: I tensorflow/core/platform/cloud/google_auth_provider.cc:180] Attempting an empty bearer token since no token was retrieved from files, and GCE metadata check was skipped.\r\n",
      "2022-08-09 18:17:45.397389: I tensorflow/core/platform/cloud/google_auth_provider.cc:180] Attempting an empty bearer token since no token was retrieved from files, and GCE metadata check was skipped.\r\n",
      "2022-08-09 18:17:45.464951: I tensorflow/core/platform/cloud/google_auth_provider.cc:180] Attempting an empty bearer token since no token was retrieved from files, and GCE metadata check was skipped.\r\n",
      "I0809 18:17:45.529721 139830674605888 dataset_builder.py:351] Reusing dataset patch (gs://kds-f2001cb46986c692a950ae60446dc32313db0b3086467d220d725445/patch/1.0.0)\r\n",
      "I0809 18:17:45.530106 139830674605888 logging_logger.py:36] Constructing tf.data.Dataset patch for split ['train', 'test', 'val'], from gs://kds-f2001cb46986c692a950ae60446dc32313db0b3086467d220d725445/patch/1.0.0\r\n",
      "2022-08-09 18:17:45.530317: I tensorflow/core/platform/cloud/google_auth_provider.cc:180] Attempting an empty bearer token since no token was retrieved from files, and GCE metadata check was skipped.\r\n",
      "Downloading data from https://storage.googleapis.com/tensorflow/keras-applications/resnet/resnet50_weights_tf_dim_ordering_tf_kernels_notop.h5\r\n",
      "94773248/94765736 [==============================] - 1s 0us/step\r\n",
      "I0809 18:17:58.219380 139830674605888 train_patch.py:145] Huấn luyện giai đoạn 1 với lớp cuối cùng\r\n",
      "Epoch 1/3\r\n",
      "445/445 [==============================] - 35s 78ms/step - loss: 0.9381 - accuracy: 0.5663 - val_loss: 0.8578 - val_accuracy: 0.6160\r\n",
      "\r\n",
      "Epoch 00001: val_accuracy improved from -inf to 0.61602, saving model to ./resnet50.h5\r\n",
      "Epoch 2/3\r\n",
      "445/445 [==============================] - 11s 25ms/step - loss: 0.8718 - accuracy: 0.6018 - val_loss: 0.8488 - val_accuracy: 0.6250\r\n",
      "\r\n",
      "Epoch 00002: val_accuracy improved from 0.61602 to 0.62500, saving model to ./resnet50.h5\r\n",
      "Epoch 3/3\r\n",
      "445/445 [==============================] - 11s 25ms/step - loss: 0.8575 - accuracy: 0.6099 - val_loss: 0.8342 - val_accuracy: 0.6357\r\n",
      "\r\n",
      "Epoch 00003: val_accuracy improved from 0.62500 to 0.63574, saving model to ./resnet50.h5\r\n",
      "I0809 18:19:02.967776 139830674605888 train_patch.py:157] Huấn luyện giai đoạn 2 mở đóng băng từ layer 0 đến top layer nb: 46\r\n",
      "Epoch 3/13\r\n",
      "445/445 [==============================] - 70s 158ms/step - loss: 0.8257 - accuracy: 0.6746 - val_loss: 0.6308 - val_accuracy: 0.7414\r\n",
      "\r\n",
      "Epoch 00003: val_accuracy improved from 0.63574 to 0.74141, saving model to ./resnet50.h5\r\n",
      "Epoch 4/13\r\n",
      "445/445 [==============================] - 12s 26ms/step - loss: 0.6148 - accuracy: 0.7499 - val_loss: 0.5575 - val_accuracy: 0.7738\r\n",
      "\r\n",
      "Epoch 00004: val_accuracy improved from 0.74141 to 0.77383, saving model to ./resnet50.h5\r\n",
      "Epoch 5/13\r\n",
      "445/445 [==============================] - 12s 26ms/step - loss: 0.5587 - accuracy: 0.7708 - val_loss: 0.5714 - val_accuracy: 0.7758\r\n",
      "\r\n",
      "Epoch 00005: val_accuracy improved from 0.77383 to 0.77578, saving model to ./resnet50.h5\r\n",
      "Epoch 6/13\r\n",
      "445/445 [==============================] - 12s 27ms/step - loss: 0.5249 - accuracy: 0.7877 - val_loss: 0.5401 - val_accuracy: 0.7795\r\n",
      "\r\n",
      "Epoch 00006: val_accuracy improved from 0.77578 to 0.77949, saving model to ./resnet50.h5\r\n",
      "Epoch 7/13\r\n",
      "445/445 [==============================] - 12s 27ms/step - loss: 0.5027 - accuracy: 0.7980 - val_loss: 0.5717 - val_accuracy: 0.7732\r\n",
      "\r\n",
      "Epoch 00007: val_accuracy did not improve from 0.77949\r\n",
      "Epoch 8/13\r\n",
      "445/445 [==============================] - 12s 26ms/step - loss: 0.4777 - accuracy: 0.8078 - val_loss: 0.5215 - val_accuracy: 0.7926\r\n",
      "\r\n",
      "Epoch 00008: val_accuracy improved from 0.77949 to 0.79258, saving model to ./resnet50.h5\r\n",
      "Epoch 9/13\r\n",
      "445/445 [==============================] - 12s 27ms/step - loss: 0.4579 - accuracy: 0.8178 - val_loss: 0.5348 - val_accuracy: 0.7955\r\n",
      "\r\n",
      "Epoch 00009: val_accuracy improved from 0.79258 to 0.79551, saving model to ./resnet50.h5\r\n",
      "Epoch 10/13\r\n",
      "445/445 [==============================] - 12s 28ms/step - loss: 0.4344 - accuracy: 0.8275 - val_loss: 0.5442 - val_accuracy: 0.7945\r\n",
      "\r\n",
      "Epoch 00010: val_accuracy did not improve from 0.79551\r\n",
      "Epoch 11/13\r\n",
      "445/445 [==============================] - 12s 26ms/step - loss: 0.4205 - accuracy: 0.8319 - val_loss: 0.5229 - val_accuracy: 0.8008\r\n",
      "\r\n",
      "Epoch 00011: val_accuracy improved from 0.79551 to 0.80078, saving model to ./resnet50.h5\r\n",
      "Epoch 12/13\r\n",
      "445/445 [==============================] - 12s 26ms/step - loss: 0.4091 - accuracy: 0.8347 - val_loss: 0.5569 - val_accuracy: 0.8002\r\n",
      "\r\n",
      "Epoch 00012: val_accuracy did not improve from 0.80078\r\n",
      "Epoch 13/13\r\n",
      "445/445 [==============================] - 12s 27ms/step - loss: 0.3875 - accuracy: 0.8465 - val_loss: 0.6871 - val_accuracy: 0.7566\r\n",
      "\r\n",
      "Epoch 00013: val_accuracy did not improve from 0.80078\r\n",
      "I0809 18:22:39.992796 139830674605888 train_patch.py:169] Mở đóng băng mô hình, huấn luyện giai đoạn 3\r\n",
      "Epoch 13/50\r\n",
      "445/445 [==============================] - 79s 178ms/step - loss: 0.4686 - accuracy: 0.8103 - val_loss: 0.5753 - val_accuracy: 0.7652\r\n",
      "\r\n",
      "Epoch 00013: val_accuracy did not improve from 0.80078\r\n",
      "Epoch 14/50\r\n",
      "445/445 [==============================] - 13s 28ms/step - loss: 0.4039 - accuracy: 0.8374 - val_loss: 0.5750 - val_accuracy: 0.7801\r\n",
      "\r\n",
      "Epoch 00014: val_accuracy did not improve from 0.80078\r\n",
      "Epoch 15/50\r\n",
      "445/445 [==============================] - 13s 29ms/step - loss: 0.3804 - accuracy: 0.8479 - val_loss: 0.5811 - val_accuracy: 0.7832\r\n",
      "\r\n",
      "Epoch 00015: val_accuracy did not improve from 0.80078\r\n",
      "Epoch 16/50\r\n",
      "445/445 [==============================] - 13s 29ms/step - loss: 0.3582 - accuracy: 0.8557 - val_loss: 0.5391 - val_accuracy: 0.7943\r\n",
      "\r\n",
      "Epoch 00016: val_accuracy did not improve from 0.80078\r\n",
      "Epoch 17/50\r\n",
      "445/445 [==============================] - 13s 30ms/step - loss: 0.3421 - accuracy: 0.8645 - val_loss: 0.4670 - val_accuracy: 0.8262\r\n",
      "\r\n",
      "Epoch 00017: val_accuracy improved from 0.80078 to 0.82617, saving model to ./resnet50.h5\r\n",
      "Epoch 18/50\r\n",
      "445/445 [==============================] - 13s 28ms/step - loss: 0.3310 - accuracy: 0.8672 - val_loss: 0.5228 - val_accuracy: 0.8041\r\n",
      "\r\n",
      "Epoch 00018: val_accuracy did not improve from 0.82617\r\n",
      "Epoch 19/50\r\n",
      "445/445 [==============================] - 13s 29ms/step - loss: 0.3177 - accuracy: 0.8782 - val_loss: 0.4898 - val_accuracy: 0.8342\r\n",
      "\r\n",
      "Epoch 00019: val_accuracy improved from 0.82617 to 0.83418, saving model to ./resnet50.h5\r\n",
      "Epoch 20/50\r\n",
      "445/445 [==============================] - 13s 28ms/step - loss: 0.3096 - accuracy: 0.8790 - val_loss: 0.4718 - val_accuracy: 0.8301\r\n",
      "\r\n",
      "Epoch 00020: val_accuracy did not improve from 0.83418\r\n",
      "Epoch 21/50\r\n",
      "445/445 [==============================] - 13s 28ms/step - loss: 0.2966 - accuracy: 0.8844 - val_loss: 0.7044 - val_accuracy: 0.7627\r\n",
      "\r\n",
      "Epoch 00021: val_accuracy did not improve from 0.83418\r\n",
      "Epoch 22/50\r\n",
      "445/445 [==============================] - 13s 28ms/step - loss: 0.2908 - accuracy: 0.8872 - val_loss: 0.4610 - val_accuracy: 0.8340\r\n",
      "\r\n",
      "Epoch 00022: val_accuracy did not improve from 0.83418\r\n",
      "Epoch 23/50\r\n",
      "445/445 [==============================] - 13s 28ms/step - loss: 0.2792 - accuracy: 0.8917 - val_loss: 0.5650 - val_accuracy: 0.8049\r\n",
      "\r\n",
      "Epoch 00023: val_accuracy did not improve from 0.83418\r\n",
      "Epoch 24/50\r\n",
      "445/445 [==============================] - 13s 28ms/step - loss: 0.2761 - accuracy: 0.8939 - val_loss: 0.5474 - val_accuracy: 0.8086\r\n",
      "\r\n",
      "Epoch 00024: val_accuracy did not improve from 0.83418\r\n",
      "Epoch 25/50\r\n",
      "445/445 [==============================] - 13s 28ms/step - loss: 0.2707 - accuracy: 0.8960 - val_loss: 0.6246 - val_accuracy: 0.7873\r\n",
      "\r\n",
      "Epoch 00025: val_accuracy did not improve from 0.83418\r\n",
      "Epoch 26/50\r\n",
      "445/445 [==============================] - 13s 28ms/step - loss: 0.2642 - accuracy: 0.8976 - val_loss: 0.5193 - val_accuracy: 0.8262\r\n",
      "\r\n",
      "Epoch 00026: val_accuracy did not improve from 0.83418\r\n",
      "Epoch 27/50\r\n",
      "445/445 [==============================] - 13s 29ms/step - loss: 0.2593 - accuracy: 0.9013 - val_loss: 1.4713 - val_accuracy: 0.6344\r\n",
      "\r\n",
      "Epoch 00027: val_accuracy did not improve from 0.83418\r\n",
      "Epoch 28/50\r\n",
      "445/445 [==============================] - 13s 28ms/step - loss: 0.2467 - accuracy: 0.9043 - val_loss: 0.7240 - val_accuracy: 0.7875\r\n",
      "\r\n",
      "Epoch 00028: val_accuracy did not improve from 0.83418\r\n",
      "Epoch 29/50\r\n",
      "445/445 [==============================] - 13s 28ms/step - loss: 0.2399 - accuracy: 0.9090 - val_loss: 0.5445 - val_accuracy: 0.8227\r\n",
      "\r\n",
      "Epoch 00029: val_accuracy did not improve from 0.83418\r\n",
      "Epoch 30/50\r\n",
      "445/445 [==============================] - 13s 28ms/step - loss: 0.2367 - accuracy: 0.9083 - val_loss: 0.6452 - val_accuracy: 0.8057\r\n",
      "\r\n",
      "Epoch 00030: val_accuracy did not improve from 0.83418\r\n",
      "Epoch 31/50\r\n",
      "445/445 [==============================] - 13s 28ms/step - loss: 0.2296 - accuracy: 0.9114 - val_loss: 1.1315 - val_accuracy: 0.7643\r\n",
      "\r\n",
      "Epoch 00031: val_accuracy did not improve from 0.83418\r\n",
      "Epoch 32/50\r\n",
      "445/445 [==============================] - 13s 28ms/step - loss: 0.2259 - accuracy: 0.9120 - val_loss: 0.7775 - val_accuracy: 0.7908\r\n",
      "\r\n",
      "Epoch 00032: val_accuracy did not improve from 0.83418\r\n",
      "I0809 18:28:37.979935 139830674605888 train_patch.py:185] Kiểm tra trên tập test\r\n",
      "148/148 [==============================] - 10s 23ms/step - loss: 0.3850 - accuracy: 0.8617\r\n"
     ]
    }
   ],
   "source": [
    "!python train_patch.py  --batch_size=64\\\n",
    "                        --model_name='resnet50'\\\n",
    "                        --drop_out=0.5\\\n",
    "                        --save_dir='./resnet50.h5'\\\n",
    "                        --num_class=3\\\n",
    "                        --lr_step1=0.001\\\n",
    "                        --lr_step2=0.0001\\\n",
    "                        --lr_step3=0.00001\\\n",
    "                        --epochs_step1=3\\\n",
    "                        --epochs_step2=10\\\n",
    "                        --epochs_step3=37"
   ]
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python 3",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.7.10"
  },
  "papermill": {
   "default_parameters": {},
   "duration": 1160.10082,
   "end_time": "2022-08-09T18:28:55.209962",
   "environment_variables": {},
   "exception": null,
   "input_path": "__notebook__.ipynb",
   "output_path": "__notebook__.ipynb",
   "parameters": {},
   "start_time": "2022-08-09T18:09:35.109142",
   "version": "2.3.3"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 5
}
